FROM quay.io/openai/universe.world-of-bits:0.20.11-4556541
COPY --chown=root:root changedFiles/run.py          /app/universe-envs/world-of-bits/bin/
COPY --chown=root:root changedFiles/core.js         /app/universe-envs/world-of-bits/static/core/
# COPY --chown=root:root changedFiles/click-test.html /app/universe-envs/world-of-bits/static/miniwob/
